name: Student Performance CI/CD

on:
  push:
    branches:
      - master

jobs:
  mlops-pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Libraries
        run: |
          pip install pandas
          pip install scikit-learn
          pip install joblib
          pip install flask

      - name: Run ML Pipeline
        run: python run_pipeline.py

      - name: Run Batch Prediction
        run: python batch_predictions.csv

      - name: Deployment Successful
        run: echo "Deployment Completed Successfully"